---

- name: Include distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include: requirements.yml

# sumo.conf is deprecated in prefence of user.properties
# This should be sym-linked by /opt/SumoCollector/config/user.properties
# in mounted into container
- name: 'Ensure sumologic_config_dir exists'
  file:
    state: directory
    dest: "{{ sumologic_config_dir }}"
    mode: 0700
    owner: "{{ sumologic_config_dir_owner }}"
  tags: [sumologic, sumologic-collector]

# task can't be idempotent
# after service start, user.properties is sanitized and accesskey automatically removed
- name: 'Template SumoCollector files'
  template:
    src: "{{ item }}"
    dest: "{{ sumologic_config_dir }}/{{ item }}"
    mode: 0700
    owner: "{{ sumologic_config_dir_owner }}"
  tags: [sumologic, sumologic-collector]
  notify: Stop SumoCollector
  with_items:
    - sumo-perf-script.sh
    - user.properties
    - sumo-env.sh
    - sumo-check-disk.sh

- name: 'Optionally stop sumo'
  command: "{{ sumologic_collector_root }}/collector stop"
  tags: [sumologic, sumologic-collector]
  when: sumologic_remove_tar_install == "yes"
  ignore_errors: yes

- name: 'Optionally delete tar install'
  file:
    state: absent
    dest: /opt/SumoCollector
  tags: [sumologic, sumologic-collector]
  when: sumologic_remove_tar_install == "yes"
  ignore_errors: yes

- name: 'Optionally delete yum install'
  yum:
    state: absent
  tags: [sumologic, sumologic-collector]
  when: sumologic_remove_yum_install == "yes"
  ignore_errors: yes

- name: 'Template cron for disk stats'
  template:
    src: etc_cron.d_disk
    dest: /etc/cron.d/disk
    mode: '0644'

- name: 'Check for SumoCollector'
  command: dpkg-query -l sumocollector
  register: sumologic_collector_deb_check
  failed_when: no
  changed_when: false
  tags: sumologic

- name: 'Download SumoCollector'
  get_url:
    url: '{{ sumocollector_installer_download }}'
    dest: '{{ sumologic_installer_remote_file }}'
  register: dl_result
  until: dl_result is success
  when: ansible_os_family == "Debian"
  tags: sumologic

- name: 'Download SumoCollector redhat'
  get_url:
    url: '{{ sumocollector_installer_rpm }}'
    dest: '{{ sumologic_installer_rpm_local_folder }}/sumo_collector.rpm'
  register: dl_result
  until: dl_result is success
  when: ansible_os_family == "RedHat"
  tags: sumologic

- name: 'Define initial SumoCollector sources'
  set_fact:
    sumologic_collector_log_paths: "{{ sumologic_collector_default_log_path|list + sumologic_collector_application_log_path|list }}"
  tags: [sumologic, sumologic-collector]

- name: 'Create collector configuration'
  template:
    src: "{{ sumologic_collector_source_template }}"
    dest: /etc/sumologic-collector.json
    mode: '0644'
  tags: [sumologic, sumologic-collector]
  notify: Stop SumoCollector
  when: sumologic_single_source_file == "yes"

- name: 'Ensure sumo sources directory exists'
  file:
    state: directory
    dest: "{{ sumologic_sources_dir }}"
    mode: '0755'
  tags: [sumologic, sumologic-collector]
  when: sumologic_single_source_file != "yes"

- name: 'Ensure sumo temp data and logs dir exists'
  file:
    state: directory
    dest: "{{ sumologic_host_dir }}"
    mode: '0755'
  tags: [sumologic, sumologic-collector]

- block:
    - name: 'Template sources'
      template:
        src: sources/{{ item | basename }}
        dest: "{{ sumologic_sources_dir }}"
        mode: '0644'
      tags: [sumologic, sumologic-collector]
      with_fileglob: ../templates/sources/*
  when: sumologic_single_source_file != "yes" and not sumologic_single_source_file

- include: linux_performance.yml
  tags: [sumologic, sumologic-collector]
  when: sumologic_do_sysstat | default(False)

- include: native_install.yml
  when: sumologic_install_method == "yum"
  tags: [sumologic, sumologic-collector]

- include: docker_install.yml
  when: sumologic_install_method == "docker"
  tags: [sumologic, sumologic-collector]

- debug:
    var: ansible_virtualization_type
    verbosity: 1
- name: 'Set udp limits for sumo (native and inherited by container)'
  sysctl:
    name: "{{ item.n }}"
    value: "{{ item.v }}"
    state: present
    sysctl_set: yes
    reload: yes
  with_items:
    - { n: 'net.core.wmem_max', v: 8388608 }
    - { n: 'net.core.rmem_max', v: 8388608 }
  tags: [sumologic, sumologic-collector]
  when: >
    (ansible_virtualization_type is not defined or
      (ansible_virtualization_type != "lxc" and
        ansible_virtualization_type != "docker" and
        ansible_virtualization_type != "VirtualPC"
      )
    )

- name: 'Ensure collector is running'
  service:
    name: "{{ item }}"
    state: started
  with_items:
    - sumologic-collector.service
  when: sumologic_install_method == "docker"
  tags: [sumologic, sumologic_docker]

- name: 'Force restart SumoCollector'
  command: "{{ sumologic_collector_root }}/collector restart"
  tags: [sumologic, sumologic-collector, sumologic_force_restart]
  when: (sumologic_force_restart == "yes") and (sumologic_install_method != "docker")

- name: 'Force restart SumoCollector docker'
  command: echo "restarting docker"
  changed_when: false
  tags: [sumologic, sumologic-collector, sumologic_force_restart]
  when: (sumologic_force_restart == "yes") and (sumologic_install_method == "docker")
  notify: 'Stop SumoCollector'

- name: 'Install SumoCollector apt'
  apt:
    deb: '{{ sumologic_installer_remote_file }}'
    state: present
  when: ansible_os_family == "Debian"
  tags: sumologic
  notify: Stop SumoCollector
  register: pkg_result
  until: pkg_result is success

- name: 'Install SumoCollector yum'
  yum:
    name: '{{ sumologic_installer_rpm_local_folder }}/sumo_collector.rpm'
    state: present
  when: ansible_os_family == "RedHat"
  tags: sumologic
  notify: Stop SumoCollector
