---

- name: Include distribution-specific variables
  include_vars: "{{ ansible_distribution }}.yml"

- include: windows.yml
  when: ansible_os_family == 'Windows'

- include: linux.yml
  when: ansible_system == 'Linux'
